version: "3"

services:
  db:
    image: postgres:16.0
    volumes:
      - project_db:/var/lib/postgresql/data
    env_file:
      - src/config/.env
    ports:
      - "5432:5432"
    networks:
      - project-network
    container_name: project-db

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    networks:
      - project-network
    depends_on:
      - db
    container_name: project-api
    restart: always

networks:
  project-network:

volumes:
  project_db: